name: nz_ua
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1


environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter_plus: ^0.3.0+2
  rxdart: ^0.27.5
  json_annotation: ^4.7.0
  dio: ^4.0.6
  prefs: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.1
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - Assets/
    - Assets/theme.tcss
    - Assets/scripts/