name: nz_ua
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1


environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
      sdk: flutter         # Add this line
  cupertino_icons: ^1.0.2
  webview_flutter_plus: ^0.3.0+2
  rxdart: ^0.27.5
  intl: ^0.17.0 # Add this line
  json_annotation: ^4.7.0
  dio: ^4.0.6
  prefs: ^3.0.0
  sqflite: ^2.1.0
  connectivity_plus: ^3.0.2
  adobe_spectrum:
    git:
      url: https://github.com/cuteUtya/flutter-adobe-spectrum
      ref: master
  design_system_provider: ^1.0.0+5

dev_dependencies:
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.1
  build_runner: ^2.3.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: SpectrumIcons
      fonts:
        - asset: fonts/SpectrumIcons.ttf
    - family: Adobe Clean
      fonts:
        - asset: fonts/AdobeClean-Light.ttf
          weight: 300
        - asset: fonts/AdobeClean-Regular.ttf
          weight: 400
        - asset: fonts/AdobeClean-Bold.ttf
          weight: 700
        - asset: fonts/AdobeClean-It.ttf
          style: italic
    - family: Source Code Pro
      fonts:
        - asset: fonts/SourceCodePro-Medium.ttf

  assets:
    - Assets/
    - Assets/theme.tcss
    - Assets/scripts/

